// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package managementsql

import (
	"context"
	"time"
)

const getArtifact = `-- name: GetArtifact :one
SELECT id, event_id, kind, created_at, content FROM artifacts WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Kind,
		&i.CreatedAt,
		&i.Content,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (id, event_id, kind, created_at, content)
VALUES (?, ?, ?, ?, ?)
RETURNING id, event_id, kind, created_at, content
`

type InsertArtifactParams struct {
	ID        string
	EventID   int64
	Kind      string
	CreatedAt time.Time
	Content   string
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, insertArtifact,
		arg.ID,
		arg.EventID,
		arg.Kind,
		arg.CreatedAt,
		arg.Content,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Kind,
		&i.CreatedAt,
		&i.Content,
	)
	return i, err
}

const listArtifactIDsByEventID = `-- name: ListArtifactIDsByEventID :many
SELECT id FROM artifacts WHERE event_id = ? ORDER BY id
`

func (q *Queries) ListArtifactIDsByEventID(ctx context.Context, eventID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactIDsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
