// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package managementsql

import (
	"context"
	"database/sql"
	"time"
)

const countDistinctTraceIDs = `-- name: CountDistinctTraceIDs :one
SELECT COUNT(DISTINCT trace_id) FROM events WHERE trace_id != ''
`

func (q *Queries) CountDistinctTraceIDs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctTraceIDs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByCategory = `-- name: CountEventsByCategory :many
SELECT category, COUNT(*) AS count FROM events GROUP BY category
`

type CountEventsByCategoryRow struct {
	Category string
	Count    int64
}

func (q *Queries) CountEventsByCategory(ctx context.Context) ([]CountEventsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countEventsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByCategoryRow{}
	for rows.Next() {
		var i CountEventsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecentErrors = `-- name: CountRecentErrors :one
SELECT COUNT(*) FROM events WHERE level = 'error'
`

func (q *Queries) CountRecentErrors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentErrors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, occurred_at, trace_id, parent_event_id, category, kind, level, module, component, tenant_id, platform, conversation_id, actor_id, subject, payload_type, payload_json, description FROM events WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.TraceID,
		&i.ParentEventID,
		&i.Category,
		&i.Kind,
		&i.Level,
		&i.Module,
		&i.Component,
		&i.TenantID,
		&i.Platform,
		&i.ConversationID,
		&i.ActorID,
		&i.Subject,
		&i.PayloadType,
		&i.PayloadJson,
		&i.Description,
	)
	return i, err
}

const getTraceEvents = `-- name: GetTraceEvents :many
SELECT id, occurred_at, trace_id, parent_event_id, category, kind, level, module, component, tenant_id, platform, conversation_id, actor_id, subject, payload_type, payload_json, description FROM events
WHERE trace_id = ?
ORDER BY id ASC
`

func (q *Queries) GetTraceEvents(ctx context.Context, traceID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getTraceEvents, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TraceID,
			&i.ParentEventID,
			&i.Category,
			&i.Kind,
			&i.Level,
			&i.Module,
			&i.Component,
			&i.TenantID,
			&i.Platform,
			&i.ConversationID,
			&i.ActorID,
			&i.Subject,
			&i.PayloadType,
			&i.PayloadJson,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
  occurred_at, trace_id, parent_event_id, category, kind, level,
  module, component, tenant_id, platform, conversation_id, actor_id,
  subject, description, payload_type, payload_json
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, occurred_at, trace_id, parent_event_id, category, kind, level, module, component, tenant_id, platform, conversation_id, actor_id, subject, payload_type, payload_json, description
`

type InsertEventParams struct {
	OccurredAt     time.Time
	TraceID        string
	ParentEventID  sql.NullInt64
	Category       string
	Kind           string
	Level          string
	Module         string
	Component      string
	TenantID       string
	Platform       string
	ConversationID string
	ActorID        string
	Subject        string
	Description    string
	PayloadType    string
	PayloadJson    string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.OccurredAt,
		arg.TraceID,
		arg.ParentEventID,
		arg.Category,
		arg.Kind,
		arg.Level,
		arg.Module,
		arg.Component,
		arg.TenantID,
		arg.Platform,
		arg.ConversationID,
		arg.ActorID,
		arg.Subject,
		arg.Description,
		arg.PayloadType,
		arg.PayloadJson,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.TraceID,
		&i.ParentEventID,
		&i.Category,
		&i.Kind,
		&i.Level,
		&i.Module,
		&i.Component,
		&i.TenantID,
		&i.Platform,
		&i.ConversationID,
		&i.ActorID,
		&i.Subject,
		&i.PayloadType,
		&i.PayloadJson,
		&i.Description,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, occurred_at, trace_id, parent_event_id, category, kind, level, module, component, tenant_id, platform, conversation_id, actor_id, subject, payload_type, payload_json, description FROM events
WHERE (?1 = '' OR category = ?1)
  AND (?2 = '' OR kind = ?2)
  AND (?3 = '' OR trace_id = ?3)
  AND (?4 = '' OR conversation_id = ?4)
  AND (?5 = '' OR module = ?5)
  AND (?6 = '' OR level = ?6)
  AND id > ?7
ORDER BY id ASC
LIMIT ?8
`

type ListEventsParams struct {
	Category       interface{}
	Kind           interface{}
	TraceID        interface{}
	ConversationID interface{}
	Module         interface{}
	Level          interface{}
	AfterID        int64
	Limit          int64
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Category,
		arg.Kind,
		arg.TraceID,
		arg.ConversationID,
		arg.Module,
		arg.Level,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TraceID,
			&i.ParentEventID,
			&i.Category,
			&i.Kind,
			&i.Level,
			&i.Module,
			&i.Component,
			&i.TenantID,
			&i.Platform,
			&i.ConversationID,
			&i.ActorID,
			&i.Subject,
			&i.PayloadType,
			&i.PayloadJson,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEventID = `-- name: MaxEventID :one
SELECT COALESCE(MAX(id), 0) FROM events
`

func (q *Queries) MaxEventID(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxEventID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const minEventID = `-- name: MinEventID :one
SELECT COALESCE(MIN(id), 0) FROM events
`

func (q *Queries) MinEventID(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, minEventID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
