// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package managementsql

import (
	"database/sql"
	"time"
)

type Artifact struct {
	ID        string
	EventID   int64
	Kind      string
	CreatedAt time.Time
	Content   string
}

type Event struct {
	ID             int64
	OccurredAt     time.Time
	TraceID        string
	ParentEventID  sql.NullInt64
	Category       string
	Kind           string
	Level          string
	Module         string
	Component      string
	TenantID       string
	Platform       string
	ConversationID string
	ActorID        string
	Subject        string
	Description    string
	PayloadJson    string
}

type Snapshot struct {
	Namespace   string
	Key         string
	Module      string
	UpdatedAt   time.Time
	Summary     string
	PayloadJson string
}
