// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package managementsql

import (
	"context"
	"time"
)

const listSnapshots = `-- name: ListSnapshots :many
SELECT namespace, "key", module, updated_at, summary, payload_json FROM snapshots
WHERE (?1 = '' OR namespace = ?1)
  AND (?2 = '' OR key = ?2)
  AND (?3 = '' OR module = ?3)
ORDER BY namespace, key
`

type ListSnapshotsParams struct {
	Namespace interface{}
	Key       interface{}
	Module    interface{}
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots, arg.Namespace, arg.Key, arg.Module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.Namespace,
			&i.Key,
			&i.Module,
			&i.UpdatedAt,
			&i.Summary,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSnapshot = `-- name: UpsertSnapshot :one
INSERT INTO snapshots (namespace, key, module, updated_at, summary, payload_json)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (namespace, key) DO UPDATE SET
  module = excluded.module,
  updated_at = excluded.updated_at,
  summary = excluded.summary,
  payload_json = excluded.payload_json
RETURNING namespace, "key", module, updated_at, summary, payload_json
`

type UpsertSnapshotParams struct {
	Namespace   string
	Key         string
	Module      string
	UpdatedAt   time.Time
	Summary     string
	PayloadJson string
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertSnapshot,
		arg.Namespace,
		arg.Key,
		arg.Module,
		arg.UpdatedAt,
		arg.Summary,
		arg.PayloadJson,
	)
	var i Snapshot
	err := row.Scan(
		&i.Namespace,
		&i.Key,
		&i.Module,
		&i.UpdatedAt,
		&i.Summary,
		&i.PayloadJson,
	)
	return i, err
}
